services:
  frontend:
    build:
      context: ./frontend
    container_name: smr-frontend
    restart: on-failure
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - ROLLUP_DISABLE_NATIVE=1
    volumes:
      - ./frontend:/app:delegated
      - bun_cache:/root/.bun
      - node_modules:/app/node_modules
    command: ["sh", "-lc", "bun install && npx vite --host 0.0.0.0 --port 5173"]
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:5173 >/dev/null 2>&1 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: smr-backend
    restart: on-failure
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./backend:/app:delegated
      - backend_db:/app/db
    command: ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8000/health/ >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30

volumes:
  bun_cache:
  node_modules:
  backend_db:



