# Generated by Django 4.2.8 on 2025-08-11 13:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this submission', primary_key=True, serialize=False)),
                ('original_text', models.TextField(help_text='The original text provided by the user for processing')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current processing status of this submission', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this submission was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this submission was last updated')),
                ('processing_started_at', models.DateTimeField(blank=True, help_text='Timestamp when processing began', null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, help_text='Timestamp when processing completed', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='text_proces_status_0edabd_idx'), models.Index(fields=['created_at'], name='text_proces_created_fb6aaf_idx')],
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary_type', models.CharField(choices=[('S1', 'Primary Summary'), ('S2', 'Secondary Summary')], help_text='Type of summary: S1 (primary) or S2 (secondary)', max_length=2)),
                ('content', models.TextField(help_text='The generated summary content')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this summary was created')),
                ('submission', models.ForeignKey(help_text='The text submission this summary belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='text_processor.textsubmission')),
            ],
            options={
                'ordering': ['summary_type', 'created_at'],
                'indexes': [models.Index(fields=['submission', 'summary_type'], name='text_proces_submiss_2145cb_idx')],
                'unique_together': {('submission', 'summary_type')},
            },
        ),
        migrations.CreateModel(
            name='Fragment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fragment_type', models.CharField(choices=[('F1', 'Extracted Fragment'), ('F2', 'Justification Fragment')], help_text='Type of fragment: F1 (extracted) or F2 (justification)', max_length=2)),
                ('content', models.TextField(help_text='The extracted fragment content (verbatim from original text)')),
                ('start_position', models.IntegerField(blank=True, help_text='Starting character position in original text (if found)', null=True)),
                ('end_position', models.IntegerField(blank=True, help_text='Ending character position in original text (if found)', null=True)),
                ('verified', models.BooleanField(default=False, help_text='Whether this fragment was mechanically verified in original text')),
                ('related_sentence', models.TextField(blank=True, help_text='For F2 fragments: the sentence from S1 this fragment justifies', null=True)),
                ('sequence_number', models.PositiveIntegerField(default=1, help_text='Order of this fragment within its type for the submission')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this fragment was created')),
                ('submission', models.ForeignKey(help_text='The text submission this fragment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='fragments', to='text_processor.textsubmission')),
            ],
            options={
                'ordering': ['fragment_type', 'sequence_number', 'created_at'],
                'indexes': [models.Index(fields=['submission', 'fragment_type'], name='text_proces_submiss_fe22ae_idx'), models.Index(fields=['verified'], name='text_proces_verifie_1bb8ae_idx')],
            },
        ),
    ]
