# Generated by Django 4.2.8 on 2024-08-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("text_processor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fragment",
            name="similarity_score",
            field=models.FloatField(
                default=0.0,
                help_text="Similarity score as percentage (0.0-100.0) indicating how closely this fragment matches the original text",
            ),
        ),
    ]
